/** Validates static native domains from pinned upstream declarations. @module */
// Generated by scripts/native-conformance.ts --static --update.
export default {
  "root": 268,
  "nodes": [
    {
      "kind": "undefined"
    },
    {
      "kind": "number"
    },
    {
      "kind": "union",
      "values": [
        0,
        1
      ]
    },
    {
      "kind": "literal",
      "value": null
    },
    {
      "kind": "string"
    },
    {
      "kind": "union",
      "values": [
        0,
        3,
        4,
        1
      ]
    },
    {
      "kind": "literal",
      "value": "visible"
    },
    {
      "kind": "literal",
      "value": "hidden"
    },
    {
      "kind": "union",
      "values": [
        0,
        6,
        7
      ]
    },
    {
      "kind": "union",
      "values": [
        0,
        4,
        1
      ]
    },
    {
      "kind": "literal",
      "value": "circular"
    },
    {
      "kind": "literal",
      "value": "continuous"
    },
    {
      "kind": "union",
      "values": [
        0,
        10,
        11
      ]
    },
    {
      "kind": "literal",
      "value": "solid"
    },
    {
      "kind": "literal",
      "value": "dotted"
    },
    {
      "kind": "literal",
      "value": "dashed"
    },
    {
      "kind": "union",
      "values": [
        0,
        13,
        14,
        15
      ]
    },
    {
      "kind": "literal",
      "value": "none"
    },
    {
      "kind": "literal",
      "value": "auto"
    },
    {
      "kind": "literal",
      "value": "box-none"
    },
    {
      "kind": "literal",
      "value": "box-only"
    },
    {
      "kind": "union",
      "values": [
        0,
        17,
        18,
        19,
        20
      ]
    },
    {
      "kind": "literal",
      "value": "isolate"
    },
    {
      "kind": "union",
      "values": [
        0,
        18,
        22
      ]
    },
    {
      "kind": "literal",
      "value": "pointer"
    },
    {
      "kind": "union",
      "values": [
        0,
        18,
        24
      ]
    },
    {
      "kind": "union",
      "values": [
        4,
        1
      ]
    },
    {
      "kind": "literal",
      "value": false
    },
    {
      "kind": "literal",
      "value": true
    },
    {
      "kind": "union",
      "values": [
        0,
        27,
        28
      ]
    },
    {
      "kind": "object",
      "properties": {
        "offsetX": {
          "optional": false,
          "value": 26
        },
        "offsetY": {
          "optional": false,
          "value": 26
        },
        "color": {
          "optional": true,
          "value": 5
        },
        "blurRadius": {
          "optional": true,
          "value": 9
        },
        "spreadDistance": {
          "optional": true,
          "value": 9
        },
        "inset": {
          "optional": true,
          "value": 29
        }
      }
    },
    {
      "kind": "array",
      "value": 30
    },
    {
      "kind": "union",
      "values": [
        0,
        4,
        31
      ]
    },
    {
      "kind": "object",
      "properties": {
        "brightness": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "blur": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "contrast": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "grayscale": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "hueRotate": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "invert": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "opacity": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "saturate": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "sepia": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "offsetX": {
          "optional": false,
          "value": 26
        },
        "offsetY": {
          "optional": false,
          "value": 26
        },
        "standardDeviation": {
          "optional": true,
          "value": 9
        },
        "color": {
          "optional": true,
          "value": 5
        }
      }
    },
    {
      "kind": "union",
      "values": [
        4,
        42
      ]
    },
    {
      "kind": "object",
      "properties": {
        "dropShadow": {
          "optional": false,
          "value": 43
        }
      }
    },
    {
      "kind": "union",
      "values": [
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        44
      ]
    },
    {
      "kind": "array",
      "value": 45
    },
    {
      "kind": "union",
      "values": [
        0,
        4,
        46
      ]
    },
    {
      "kind": "literal",
      "value": "normal"
    },
    {
      "kind": "literal",
      "value": "multiply"
    },
    {
      "kind": "literal",
      "value": "screen"
    },
    {
      "kind": "literal",
      "value": "overlay"
    },
    {
      "kind": "literal",
      "value": "darken"
    },
    {
      "kind": "literal",
      "value": "lighten"
    },
    {
      "kind": "literal",
      "value": "color-dodge"
    },
    {
      "kind": "literal",
      "value": "color-burn"
    },
    {
      "kind": "literal",
      "value": "hard-light"
    },
    {
      "kind": "literal",
      "value": "soft-light"
    },
    {
      "kind": "literal",
      "value": "difference"
    },
    {
      "kind": "literal",
      "value": "exclusion"
    },
    {
      "kind": "literal",
      "value": "hue"
    },
    {
      "kind": "literal",
      "value": "saturation"
    },
    {
      "kind": "literal",
      "value": "color"
    },
    {
      "kind": "literal",
      "value": "luminosity"
    },
    {
      "kind": "literal",
      "value": "plus-lighter"
    },
    {
      "kind": "union",
      "values": [
        0,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64
      ]
    },
    {
      "kind": "literal",
      "value": "linear-gradient"
    },
    {
      "kind": "union",
      "values": [
        0,
        4
      ]
    },
    {
      "kind": "union",
      "values": [
        3,
        4,
        1
      ]
    },
    {
      "kind": "array",
      "value": 4
    },
    {
      "kind": "union",
      "values": [
        0,
        69
      ]
    },
    {
      "kind": "object",
      "properties": {
        "color": {
          "optional": false,
          "value": 68
        },
        "positions": {
          "optional": true,
          "value": 70
        }
      }
    },
    {
      "kind": "array",
      "value": 71
    },
    {
      "kind": "object",
      "properties": {
        "type": {
          "optional": false,
          "value": 66
        },
        "direction": {
          "optional": true,
          "value": 67
        },
        "colorStops": {
          "optional": false,
          "value": 72
        }
      }
    },
    {
      "kind": "literal",
      "value": "radial-gradient"
    },
    {
      "kind": "literal",
      "value": "circle"
    },
    {
      "kind": "literal",
      "value": "ellipse"
    },
    {
      "kind": "union",
      "values": [
        75,
        76
      ]
    },
    {
      "kind": "literal",
      "value": "closest-corner"
    },
    {
      "kind": "literal",
      "value": "closest-side"
    },
    {
      "kind": "literal",
      "value": "farthest-corner"
    },
    {
      "kind": "literal",
      "value": "farthest-side"
    },
    {
      "kind": "object",
      "properties": {
        "x": {
          "optional": false,
          "value": 26
        },
        "y": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "union",
      "values": [
        78,
        79,
        80,
        81,
        82
      ]
    },
    {
      "kind": "object",
      "properties": {
        "top": {
          "optional": false,
          "value": 26
        },
        "left": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "top": {
          "optional": false,
          "value": 26
        },
        "right": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "bottom": {
          "optional": false,
          "value": 26
        },
        "left": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "bottom": {
          "optional": false,
          "value": 26
        },
        "right": {
          "optional": false,
          "value": 26
        }
      }
    },
    {
      "kind": "union",
      "values": [
        84,
        85,
        86,
        87
      ]
    },
    {
      "kind": "object",
      "properties": {
        "type": {
          "optional": false,
          "value": 74
        },
        "shape": {
          "optional": false,
          "value": 77
        },
        "size": {
          "optional": false,
          "value": 83
        },
        "position": {
          "optional": false,
          "value": 88
        },
        "colorStops": {
          "optional": false,
          "value": 72
        }
      }
    },
    {
      "kind": "union",
      "values": [
        73,
        89
      ]
    },
    {
      "kind": "array",
      "value": 90
    },
    {
      "kind": "union",
      "values": [
        0,
        4,
        91
      ]
    },
    {
      "kind": "array",
      "value": 82
    },
    {
      "kind": "union",
      "values": [
        0,
        4,
        93
      ]
    },
    {
      "kind": "array",
      "value": 88
    },
    {
      "kind": "union",
      "values": [
        0,
        4,
        95
      ]
    },
    {
      "kind": "literal",
      "value": "repeat"
    },
    {
      "kind": "literal",
      "value": "space"
    },
    {
      "kind": "literal",
      "value": "round"
    },
    {
      "kind": "literal",
      "value": "no-repeat"
    },
    {
      "kind": "union",
      "values": [
        97,
        98,
        99,
        100
      ]
    },
    {
      "kind": "object",
      "properties": {
        "x": {
          "optional": false,
          "value": 101
        },
        "y": {
          "optional": false,
          "value": 101
        }
      }
    },
    {
      "kind": "array",
      "value": 102
    },
    {
      "kind": "union",
      "values": [
        0,
        4,
        103
      ]
    },
    {
      "kind": "literal",
      "value": "stretch"
    },
    {
      "kind": "literal",
      "value": "center"
    },
    {
      "kind": "literal",
      "value": "flex-start"
    },
    {
      "kind": "literal",
      "value": "flex-end"
    },
    {
      "kind": "literal",
      "value": "space-between"
    },
    {
      "kind": "literal",
      "value": "space-around"
    },
    {
      "kind": "literal",
      "value": "space-evenly"
    },
    {
      "kind": "union",
      "values": [
        0,
        105,
        106,
        107,
        108,
        109,
        110,
        111
      ]
    },
    {
      "kind": "literal",
      "value": "baseline"
    },
    {
      "kind": "union",
      "values": [
        0,
        105,
        106,
        107,
        108,
        113
      ]
    },
    {
      "kind": "union",
      "values": [
        0,
        105,
        106,
        107,
        108,
        113,
        18
      ]
    },
    {
      "kind": "literal",
      "value": "border-box"
    },
    {
      "kind": "literal",
      "value": "content-box"
    },
    {
      "kind": "union",
      "values": [
        0,
        116,
        117
      ]
    },
    {
      "kind": "literal",
      "value": "flex"
    },
    {
      "kind": "literal",
      "value": "contents"
    },
    {
      "kind": "union",
      "values": [
        0,
        17,
        119,
        120
      ]
    },
    {
      "kind": "literal",
      "value": "row"
    },
    {
      "kind": "literal",
      "value": "column"
    },
    {
      "kind": "literal",
      "value": "row-reverse"
    },
    {
      "kind": "literal",
      "value": "column-reverse"
    },
    {
      "kind": "union",
      "values": [
        0,
        122,
        123,
        124,
        125
      ]
    },
    {
      "kind": "literal",
      "value": "wrap"
    },
    {
      "kind": "literal",
      "value": "nowrap"
    },
    {
      "kind": "literal",
      "value": "wrap-reverse"
    },
    {
      "kind": "union",
      "values": [
        0,
        127,
        128,
        129
      ]
    },
    {
      "kind": "union",
      "values": [
        0,
        106,
        107,
        108,
        109,
        110,
        111
      ]
    },
    {
      "kind": "literal",
      "value": "scroll"
    },
    {
      "kind": "union",
      "values": [
        0,
        6,
        7,
        132
      ]
    },
    {
      "kind": "literal",
      "value": "absolute"
    },
    {
      "kind": "literal",
      "value": "relative"
    },
    {
      "kind": "literal",
      "value": "static"
    },
    {
      "kind": "union",
      "values": [
        0,
        134,
        135,
        136
      ]
    },
    {
      "kind": "literal",
      "value": "inherit"
    },
    {
      "kind": "literal",
      "value": "ltr"
    },
    {
      "kind": "literal",
      "value": "rtl"
    },
    {
      "kind": "union",
      "values": [
        0,
        138,
        139,
        140
      ]
    },
    {
      "kind": "object",
      "properties": {
        "width": {
          "optional": true,
          "value": 2
        },
        "height": {
          "optional": true,
          "value": 2
        }
      }
    },
    {
      "kind": "union",
      "values": [
        0,
        142
      ]
    },
    {
      "kind": "literal",
      "value": "small-caps"
    },
    {
      "kind": "literal",
      "value": "oldstyle-nums"
    },
    {
      "kind": "literal",
      "value": "lining-nums"
    },
    {
      "kind": "literal",
      "value": "tabular-nums"
    },
    {
      "kind": "literal",
      "value": "common-ligatures"
    },
    {
      "kind": "literal",
      "value": "no-common-ligatures"
    },
    {
      "kind": "literal",
      "value": "discretionary-ligatures"
    },
    {
      "kind": "literal",
      "value": "no-discretionary-ligatures"
    },
    {
      "kind": "literal",
      "value": "historical-ligatures"
    },
    {
      "kind": "literal",
      "value": "no-historical-ligatures"
    },
    {
      "kind": "literal",
      "value": "contextual"
    },
    {
      "kind": "literal",
      "value": "no-contextual"
    },
    {
      "kind": "literal",
      "value": "proportional-nums"
    },
    {
      "kind": "literal",
      "value": "stylistic-one"
    },
    {
      "kind": "literal",
      "value": "stylistic-two"
    },
    {
      "kind": "literal",
      "value": "stylistic-three"
    },
    {
      "kind": "literal",
      "value": "stylistic-four"
    },
    {
      "kind": "literal",
      "value": "stylistic-five"
    },
    {
      "kind": "literal",
      "value": "stylistic-six"
    },
    {
      "kind": "literal",
      "value": "stylistic-seven"
    },
    {
      "kind": "literal",
      "value": "stylistic-eight"
    },
    {
      "kind": "literal",
      "value": "stylistic-nine"
    },
    {
      "kind": "literal",
      "value": "stylistic-ten"
    },
    {
      "kind": "literal",
      "value": "stylistic-eleven"
    },
    {
      "kind": "literal",
      "value": "stylistic-twelve"
    },
    {
      "kind": "literal",
      "value": "stylistic-thirteen"
    },
    {
      "kind": "literal",
      "value": "stylistic-fourteen"
    },
    {
      "kind": "literal",
      "value": "stylistic-fifteen"
    },
    {
      "kind": "literal",
      "value": "stylistic-sixteen"
    },
    {
      "kind": "literal",
      "value": "stylistic-seventeen"
    },
    {
      "kind": "literal",
      "value": "stylistic-eighteen"
    },
    {
      "kind": "literal",
      "value": "stylistic-nineteen"
    },
    {
      "kind": "literal",
      "value": "stylistic-twenty"
    },
    {
      "kind": "union",
      "values": [
        144,
        145,
        146,
        147,
        148,
        149,
        150,
        151,
        152,
        153,
        154,
        155,
        156,
        157,
        158,
        159,
        160,
        161,
        162,
        163,
        164,
        165,
        166,
        167,
        168,
        169,
        170,
        171,
        172,
        173,
        174,
        175,
        176
      ]
    },
    {
      "kind": "array",
      "value": 177
    },
    {
      "kind": "union",
      "values": [
        0,
        4,
        178
      ]
    },
    {
      "kind": "literal",
      "value": "double"
    },
    {
      "kind": "literal",
      "value": "wavy"
    },
    {
      "kind": "union",
      "values": [
        0,
        13,
        14,
        15,
        180,
        181
      ]
    },
    {
      "kind": "union",
      "values": [
        0,
        18,
        139,
        140
      ]
    },
    {
      "kind": "literal",
      "value": "bottom"
    },
    {
      "kind": "literal",
      "value": "top"
    },
    {
      "kind": "union",
      "values": [
        0,
        106,
        18,
        184,
        185
      ]
    },
    {
      "kind": "literal",
      "value": "middle"
    },
    {
      "kind": "union",
      "values": [
        0,
        18,
        184,
        185,
        187
      ]
    },
    {
      "kind": "literal",
      "value": "italic"
    },
    {
      "kind": "union",
      "values": [
        0,
        48,
        189
      ]
    },
    {
      "kind": "literal",
      "value": "bold"
    },
    {
      "kind": "literal",
      "value": "100"
    },
    {
      "kind": "literal",
      "value": "200"
    },
    {
      "kind": "literal",
      "value": "300"
    },
    {
      "kind": "literal",
      "value": "400"
    },
    {
      "kind": "literal",
      "value": "500"
    },
    {
      "kind": "literal",
      "value": "600"
    },
    {
      "kind": "literal",
      "value": "700"
    },
    {
      "kind": "literal",
      "value": "800"
    },
    {
      "kind": "literal",
      "value": "900"
    },
    {
      "kind": "literal",
      "value": 100
    },
    {
      "kind": "literal",
      "value": 200
    },
    {
      "kind": "literal",
      "value": 300
    },
    {
      "kind": "literal",
      "value": 400
    },
    {
      "kind": "literal",
      "value": 500
    },
    {
      "kind": "literal",
      "value": 600
    },
    {
      "kind": "literal",
      "value": 700
    },
    {
      "kind": "literal",
      "value": 800
    },
    {
      "kind": "literal",
      "value": 900
    },
    {
      "kind": "literal",
      "value": "ultralight"
    },
    {
      "kind": "literal",
      "value": "thin"
    },
    {
      "kind": "literal",
      "value": "light"
    },
    {
      "kind": "literal",
      "value": "medium"
    },
    {
      "kind": "literal",
      "value": "regular"
    },
    {
      "kind": "literal",
      "value": "semibold"
    },
    {
      "kind": "literal",
      "value": "condensedBold"
    },
    {
      "kind": "literal",
      "value": "condensed"
    },
    {
      "kind": "literal",
      "value": "heavy"
    },
    {
      "kind": "literal",
      "value": "black"
    },
    {
      "kind": "union",
      "values": [
        0,
        48,
        191,
        192,
        193,
        194,
        195,
        196,
        197,
        198,
        199,
        200,
        201,
        202,
        203,
        204,
        205,
        206,
        207,
        208,
        209,
        210,
        211,
        212,
        213,
        214,
        215,
        216,
        217,
        218,
        219
      ]
    },
    {
      "kind": "literal",
      "value": "end"
    },
    {
      "kind": "literal",
      "value": "left"
    },
    {
      "kind": "literal",
      "value": "right"
    },
    {
      "kind": "literal",
      "value": "start"
    },
    {
      "kind": "literal",
      "value": "justify"
    },
    {
      "kind": "union",
      "values": [
        0,
        106,
        18,
        221,
        222,
        223,
        224,
        225
      ]
    },
    {
      "kind": "literal",
      "value": "underline"
    },
    {
      "kind": "literal",
      "value": "line-through"
    },
    {
      "kind": "literal",
      "value": "underline line-through"
    },
    {
      "kind": "union",
      "values": [
        0,
        17,
        227,
        228,
        229
      ]
    },
    {
      "kind": "object",
      "properties": {
        "width": {
          "optional": false,
          "value": 1
        },
        "height": {
          "optional": false,
          "value": 1
        }
      }
    },
    {
      "kind": "union",
      "values": [
        0,
        231
      ]
    },
    {
      "kind": "literal",
      "value": "capitalize"
    },
    {
      "kind": "literal",
      "value": "uppercase"
    },
    {
      "kind": "literal",
      "value": "lowercase"
    },
    {
      "kind": "union",
      "values": [
        0,
        17,
        233,
        234,
        235
      ]
    },
    {
      "kind": "literal",
      "value": "contain"
    },
    {
      "kind": "literal",
      "value": "text"
    },
    {
      "kind": "literal",
      "value": "all"
    },
    {
      "kind": "union",
      "values": [
        0,
        237,
        17,
        18,
        238,
        239
      ]
    },
    {
      "kind": "literal",
      "value": "cover"
    },
    {
      "kind": "union",
      "values": [
        0,
        241,
        237,
        105,
        97,
        106,
        17
      ]
    },
    {
      "kind": "literal",
      "value": "fill"
    },
    {
      "kind": "literal",
      "value": "scale-down"
    },
    {
      "kind": "union",
      "values": [
        0,
        241,
        237,
        17,
        243,
        244
      ]
    },
    {
      "kind": "object",
      "properties": {
        "perspective": {
          "optional": false,
          "value": 1
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "rotate": {
          "optional": false,
          "value": 4
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "rotateX": {
          "optional": false,
          "value": 4
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "rotateY": {
          "optional": false,
          "value": 4
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "rotateZ": {
          "optional": false,
          "value": 4
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "scale": {
          "optional": false,
          "value": 1
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "scaleX": {
          "optional": false,
          "value": 1
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "scaleY": {
          "optional": false,
          "value": 1
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "translateX": {
          "optional": false,
          "value": 26
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "translateY": {
          "optional": false,
          "value": 26
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "skewX": {
          "optional": false,
          "value": 4
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "skewY": {
          "optional": false,
          "value": 4
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "array",
      "value": 1
    },
    {
      "kind": "object",
      "properties": {
        "matrix": {
          "optional": false,
          "value": 258
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "translate": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "tuple",
      "values": [
        26,
        26
      ]
    },
    {
      "kind": "object",
      "properties": {
        "translate": {
          "optional": false,
          "value": 260
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "union",
      "values": [
        246,
        247,
        248,
        249,
        250,
        251,
        252,
        253,
        254,
        255,
        256,
        257,
        259,
        261
      ]
    },
    {
      "kind": "array",
      "value": 262
    },
    {
      "kind": "union",
      "values": [
        0,
        4,
        263
      ]
    },
    {
      "kind": "tuple",
      "values": [
        26,
        26,
        26
      ]
    },
    {
      "kind": "union",
      "values": [
        0,
        4,
        265
      ]
    },
    {
      "kind": "union",
      "values": [
        0,
        258
      ]
    },
    {
      "kind": "object",
      "properties": {
        "flex": {
          "optional": true,
          "value": 2
        },
        "scaleX": {
          "optional": true,
          "value": 2
        },
        "scaleY": {
          "optional": true,
          "value": 2
        },
        "translateX": {
          "optional": true,
          "value": 2
        },
        "translateY": {
          "optional": true,
          "value": 2
        },
        "color": {
          "optional": true,
          "value": 5
        },
        "backfaceVisibility": {
          "optional": true,
          "value": 8
        },
        "backgroundColor": {
          "optional": true,
          "value": 5
        },
        "borderBlockColor": {
          "optional": true,
          "value": 5
        },
        "borderBlockEndColor": {
          "optional": true,
          "value": 5
        },
        "borderBlockStartColor": {
          "optional": true,
          "value": 5
        },
        "borderBottomColor": {
          "optional": true,
          "value": 5
        },
        "borderBottomEndRadius": {
          "optional": true,
          "value": 9
        },
        "borderBottomLeftRadius": {
          "optional": true,
          "value": 9
        },
        "borderBottomRightRadius": {
          "optional": true,
          "value": 9
        },
        "borderBottomStartRadius": {
          "optional": true,
          "value": 9
        },
        "borderColor": {
          "optional": true,
          "value": 5
        },
        "borderCurve": {
          "optional": true,
          "value": 12
        },
        "borderEndColor": {
          "optional": true,
          "value": 5
        },
        "borderEndEndRadius": {
          "optional": true,
          "value": 9
        },
        "borderEndStartRadius": {
          "optional": true,
          "value": 9
        },
        "borderLeftColor": {
          "optional": true,
          "value": 5
        },
        "borderRadius": {
          "optional": true,
          "value": 9
        },
        "borderRightColor": {
          "optional": true,
          "value": 5
        },
        "borderStartColor": {
          "optional": true,
          "value": 5
        },
        "borderStartEndRadius": {
          "optional": true,
          "value": 9
        },
        "borderStartStartRadius": {
          "optional": true,
          "value": 9
        },
        "borderStyle": {
          "optional": true,
          "value": 16
        },
        "borderTopColor": {
          "optional": true,
          "value": 5
        },
        "borderTopEndRadius": {
          "optional": true,
          "value": 9
        },
        "borderTopLeftRadius": {
          "optional": true,
          "value": 9
        },
        "borderTopRightRadius": {
          "optional": true,
          "value": 9
        },
        "borderTopStartRadius": {
          "optional": true,
          "value": 9
        },
        "outlineColor": {
          "optional": true,
          "value": 5
        },
        "outlineOffset": {
          "optional": true,
          "value": 2
        },
        "outlineStyle": {
          "optional": true,
          "value": 16
        },
        "outlineWidth": {
          "optional": true,
          "value": 2
        },
        "opacity": {
          "optional": true,
          "value": 2
        },
        "elevation": {
          "optional": true,
          "value": 2
        },
        "pointerEvents": {
          "optional": true,
          "value": 21
        },
        "isolation": {
          "optional": true,
          "value": 23
        },
        "cursor": {
          "optional": true,
          "value": 25
        },
        "boxShadow": {
          "optional": true,
          "value": 32
        },
        "filter": {
          "optional": true,
          "value": 47
        },
        "mixBlendMode": {
          "optional": true,
          "value": 65
        },
        "backgroundImage": {
          "optional": true,
          "value": 92
        },
        "experimental_backgroundImage": {
          "optional": true,
          "value": 92
        },
        "experimental_backgroundSize": {
          "optional": true,
          "value": 94
        },
        "experimental_backgroundPosition": {
          "optional": true,
          "value": 96
        },
        "experimental_backgroundRepeat": {
          "optional": true,
          "value": 104
        },
        "alignContent": {
          "optional": true,
          "value": 112
        },
        "alignItems": {
          "optional": true,
          "value": 114
        },
        "alignSelf": {
          "optional": true,
          "value": 115
        },
        "aspectRatio": {
          "optional": true,
          "value": 9
        },
        "borderBottomWidth": {
          "optional": true,
          "value": 2
        },
        "borderEndWidth": {
          "optional": true,
          "value": 2
        },
        "borderLeftWidth": {
          "optional": true,
          "value": 2
        },
        "borderRightWidth": {
          "optional": true,
          "value": 2
        },
        "borderStartWidth": {
          "optional": true,
          "value": 2
        },
        "borderTopWidth": {
          "optional": true,
          "value": 2
        },
        "borderWidth": {
          "optional": true,
          "value": 2
        },
        "bottom": {
          "optional": true,
          "value": 5
        },
        "boxSizing": {
          "optional": true,
          "value": 118
        },
        "display": {
          "optional": true,
          "value": 121
        },
        "end": {
          "optional": true,
          "value": 5
        },
        "flexBasis": {
          "optional": true,
          "value": 9
        },
        "flexDirection": {
          "optional": true,
          "value": 126
        },
        "rowGap": {
          "optional": true,
          "value": 9
        },
        "gap": {
          "optional": true,
          "value": 9
        },
        "columnGap": {
          "optional": true,
          "value": 9
        },
        "flexGrow": {
          "optional": true,
          "value": 2
        },
        "flexShrink": {
          "optional": true,
          "value": 2
        },
        "flexWrap": {
          "optional": true,
          "value": 130
        },
        "height": {
          "optional": true,
          "value": 5
        },
        "justifyContent": {
          "optional": true,
          "value": 131
        },
        "left": {
          "optional": true,
          "value": 5
        },
        "margin": {
          "optional": true,
          "value": 5
        },
        "marginBottom": {
          "optional": true,
          "value": 5
        },
        "marginEnd": {
          "optional": true,
          "value": 5
        },
        "marginHorizontal": {
          "optional": true,
          "value": 5
        },
        "marginLeft": {
          "optional": true,
          "value": 5
        },
        "marginRight": {
          "optional": true,
          "value": 5
        },
        "marginStart": {
          "optional": true,
          "value": 5
        },
        "marginTop": {
          "optional": true,
          "value": 5
        },
        "marginVertical": {
          "optional": true,
          "value": 5
        },
        "maxHeight": {
          "optional": true,
          "value": 5
        },
        "maxWidth": {
          "optional": true,
          "value": 5
        },
        "minHeight": {
          "optional": true,
          "value": 5
        },
        "minWidth": {
          "optional": true,
          "value": 5
        },
        "overflow": {
          "optional": true,
          "value": 133
        },
        "padding": {
          "optional": true,
          "value": 5
        },
        "paddingBottom": {
          "optional": true,
          "value": 5
        },
        "paddingEnd": {
          "optional": true,
          "value": 5
        },
        "paddingHorizontal": {
          "optional": true,
          "value": 5
        },
        "paddingLeft": {
          "optional": true,
          "value": 5
        },
        "paddingRight": {
          "optional": true,
          "value": 5
        },
        "paddingStart": {
          "optional": true,
          "value": 5
        },
        "paddingTop": {
          "optional": true,
          "value": 5
        },
        "paddingVertical": {
          "optional": true,
          "value": 5
        },
        "position": {
          "optional": true,
          "value": 137
        },
        "right": {
          "optional": true,
          "value": 5
        },
        "start": {
          "optional": true,
          "value": 5
        },
        "top": {
          "optional": true,
          "value": 5
        },
        "width": {
          "optional": true,
          "value": 5
        },
        "zIndex": {
          "optional": true,
          "value": 2
        },
        "direction": {
          "optional": true,
          "value": 141
        },
        "inset": {
          "optional": true,
          "value": 5
        },
        "insetBlock": {
          "optional": true,
          "value": 5
        },
        "insetBlockEnd": {
          "optional": true,
          "value": 5
        },
        "insetBlockStart": {
          "optional": true,
          "value": 5
        },
        "insetInline": {
          "optional": true,
          "value": 5
        },
        "insetInlineEnd": {
          "optional": true,
          "value": 5
        },
        "insetInlineStart": {
          "optional": true,
          "value": 5
        },
        "marginBlock": {
          "optional": true,
          "value": 5
        },
        "marginBlockEnd": {
          "optional": true,
          "value": 5
        },
        "marginBlockStart": {
          "optional": true,
          "value": 5
        },
        "marginInline": {
          "optional": true,
          "value": 5
        },
        "marginInlineEnd": {
          "optional": true,
          "value": 5
        },
        "marginInlineStart": {
          "optional": true,
          "value": 5
        },
        "paddingBlock": {
          "optional": true,
          "value": 5
        },
        "paddingBlockEnd": {
          "optional": true,
          "value": 5
        },
        "paddingBlockStart": {
          "optional": true,
          "value": 5
        },
        "paddingInline": {
          "optional": true,
          "value": 5
        },
        "paddingInlineEnd": {
          "optional": true,
          "value": 5
        },
        "paddingInlineStart": {
          "optional": true,
          "value": 5
        },
        "shadowColor": {
          "optional": true,
          "value": 5
        },
        "shadowOffset": {
          "optional": true,
          "value": 143
        },
        "shadowOpacity": {
          "optional": true,
          "value": 2
        },
        "shadowRadius": {
          "optional": true,
          "value": 2
        },
        "fontVariant": {
          "optional": true,
          "value": 179
        },
        "textDecorationColor": {
          "optional": true,
          "value": 5
        },
        "textDecorationStyle": {
          "optional": true,
          "value": 182
        },
        "writingDirection": {
          "optional": true,
          "value": 183
        },
        "textAlignVertical": {
          "optional": true,
          "value": 186
        },
        "verticalAlign": {
          "optional": true,
          "value": 188
        },
        "includeFontPadding": {
          "optional": true,
          "value": 29
        },
        "fontFamily": {
          "optional": true,
          "value": 67
        },
        "fontSize": {
          "optional": true,
          "value": 2
        },
        "fontStyle": {
          "optional": true,
          "value": 190
        },
        "fontWeight": {
          "optional": true,
          "value": 220
        },
        "letterSpacing": {
          "optional": true,
          "value": 2
        },
        "lineHeight": {
          "optional": true,
          "value": 2
        },
        "textAlign": {
          "optional": true,
          "value": 226
        },
        "textDecorationLine": {
          "optional": true,
          "value": 230
        },
        "textShadowColor": {
          "optional": true,
          "value": 5
        },
        "textShadowOffset": {
          "optional": true,
          "value": 232
        },
        "textShadowRadius": {
          "optional": true,
          "value": 2
        },
        "textTransform": {
          "optional": true,
          "value": 236
        },
        "userSelect": {
          "optional": true,
          "value": 240
        },
        "resizeMode": {
          "optional": true,
          "value": 242
        },
        "overlayColor": {
          "optional": true,
          "value": 5
        },
        "tintColor": {
          "optional": true,
          "value": 5
        },
        "objectFit": {
          "optional": true,
          "value": 245
        },
        "transform": {
          "optional": true,
          "value": 264
        },
        "transformOrigin": {
          "optional": true,
          "value": 266
        },
        "transformMatrix": {
          "optional": true,
          "value": 267
        },
        "rotation": {
          "optional": true,
          "value": 2
        }
      }
    }
  ]
}
