/** Validates static native domains from pinned upstream declarations. @module */
// Generated by scripts/native-conformance.ts --static --update.
export default {
  "root": 266,
  "nodes": [
    {
      "kind": "undefined"
    },
    {
      "kind": "number"
    },
    {
      "kind": "union",
      "values": [
        0,
        1
      ]
    },
    {
      "kind": "string"
    },
    {
      "kind": "union",
      "values": [
        0,
        3
      ]
    },
    {
      "kind": "literal",
      "value": "visible"
    },
    {
      "kind": "literal",
      "value": "hidden"
    },
    {
      "kind": "union",
      "values": [
        0,
        5,
        6
      ]
    },
    {
      "kind": "union",
      "values": [
        0,
        3,
        1
      ]
    },
    {
      "kind": "literal",
      "value": "circular"
    },
    {
      "kind": "literal",
      "value": "continuous"
    },
    {
      "kind": "union",
      "values": [
        0,
        9,
        10
      ]
    },
    {
      "kind": "literal",
      "value": "solid"
    },
    {
      "kind": "literal",
      "value": "dotted"
    },
    {
      "kind": "literal",
      "value": "dashed"
    },
    {
      "kind": "union",
      "values": [
        0,
        12,
        13,
        14
      ]
    },
    {
      "kind": "literal",
      "value": "none"
    },
    {
      "kind": "literal",
      "value": "auto"
    },
    {
      "kind": "literal",
      "value": "box-none"
    },
    {
      "kind": "literal",
      "value": "box-only"
    },
    {
      "kind": "union",
      "values": [
        0,
        16,
        17,
        18,
        19
      ]
    },
    {
      "kind": "literal",
      "value": "isolate"
    },
    {
      "kind": "union",
      "values": [
        0,
        17,
        21
      ]
    },
    {
      "kind": "literal",
      "value": "pointer"
    },
    {
      "kind": "union",
      "values": [
        0,
        17,
        23
      ]
    },
    {
      "kind": "union",
      "values": [
        3,
        1
      ]
    },
    {
      "kind": "literal",
      "value": false
    },
    {
      "kind": "literal",
      "value": true
    },
    {
      "kind": "union",
      "values": [
        0,
        26,
        27
      ]
    },
    {
      "kind": "object",
      "properties": {
        "offsetX": {
          "optional": false,
          "value": 25
        },
        "offsetY": {
          "optional": false,
          "value": 25
        },
        "color": {
          "optional": true,
          "value": 4
        },
        "blurRadius": {
          "optional": true,
          "value": 8
        },
        "spreadDistance": {
          "optional": true,
          "value": 8
        },
        "inset": {
          "optional": true,
          "value": 28
        }
      }
    },
    {
      "kind": "array",
      "value": 29
    },
    {
      "kind": "union",
      "values": [
        0,
        3,
        30
      ]
    },
    {
      "kind": "object",
      "properties": {
        "brightness": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "blur": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "contrast": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "grayscale": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "hueRotate": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "invert": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "opacity": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "saturate": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "sepia": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "offsetX": {
          "optional": false,
          "value": 25
        },
        "offsetY": {
          "optional": false,
          "value": 25
        },
        "standardDeviation": {
          "optional": true,
          "value": 8
        },
        "color": {
          "optional": true,
          "value": 8
        }
      }
    },
    {
      "kind": "union",
      "values": [
        3,
        41
      ]
    },
    {
      "kind": "object",
      "properties": {
        "dropShadow": {
          "optional": false,
          "value": 42
        }
      }
    },
    {
      "kind": "union",
      "values": [
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        43
      ]
    },
    {
      "kind": "array",
      "value": 44
    },
    {
      "kind": "union",
      "values": [
        0,
        3,
        45
      ]
    },
    {
      "kind": "literal",
      "value": "normal"
    },
    {
      "kind": "literal",
      "value": "multiply"
    },
    {
      "kind": "literal",
      "value": "screen"
    },
    {
      "kind": "literal",
      "value": "overlay"
    },
    {
      "kind": "literal",
      "value": "darken"
    },
    {
      "kind": "literal",
      "value": "lighten"
    },
    {
      "kind": "literal",
      "value": "color-dodge"
    },
    {
      "kind": "literal",
      "value": "color-burn"
    },
    {
      "kind": "literal",
      "value": "hard-light"
    },
    {
      "kind": "literal",
      "value": "soft-light"
    },
    {
      "kind": "literal",
      "value": "difference"
    },
    {
      "kind": "literal",
      "value": "exclusion"
    },
    {
      "kind": "literal",
      "value": "hue"
    },
    {
      "kind": "literal",
      "value": "saturation"
    },
    {
      "kind": "literal",
      "value": "color"
    },
    {
      "kind": "literal",
      "value": "luminosity"
    },
    {
      "kind": "literal",
      "value": "plus-lighter"
    },
    {
      "kind": "union",
      "values": [
        0,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63
      ]
    },
    {
      "kind": "literal",
      "value": "linear-gradient"
    },
    {
      "kind": "literal",
      "value": null
    },
    {
      "kind": "union",
      "values": [
        66,
        3
      ]
    },
    {
      "kind": "array",
      "value": 3
    },
    {
      "kind": "union",
      "values": [
        0,
        68
      ]
    },
    {
      "kind": "object",
      "properties": {
        "color": {
          "optional": false,
          "value": 67
        },
        "positions": {
          "optional": true,
          "value": 69
        }
      }
    },
    {
      "kind": "array",
      "value": 70
    },
    {
      "kind": "object",
      "properties": {
        "type": {
          "optional": false,
          "value": 65
        },
        "direction": {
          "optional": true,
          "value": 4
        },
        "colorStops": {
          "optional": false,
          "value": 71
        }
      }
    },
    {
      "kind": "literal",
      "value": "radial-gradient"
    },
    {
      "kind": "literal",
      "value": "circle"
    },
    {
      "kind": "literal",
      "value": "ellipse"
    },
    {
      "kind": "union",
      "values": [
        74,
        75
      ]
    },
    {
      "kind": "literal",
      "value": "closest-corner"
    },
    {
      "kind": "literal",
      "value": "closest-side"
    },
    {
      "kind": "literal",
      "value": "farthest-corner"
    },
    {
      "kind": "literal",
      "value": "farthest-side"
    },
    {
      "kind": "object",
      "properties": {
        "x": {
          "optional": false,
          "value": 25
        },
        "y": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "union",
      "values": [
        77,
        78,
        79,
        80,
        81
      ]
    },
    {
      "kind": "object",
      "properties": {
        "top": {
          "optional": false,
          "value": 25
        },
        "left": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "top": {
          "optional": false,
          "value": 25
        },
        "right": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "bottom": {
          "optional": false,
          "value": 25
        },
        "left": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "bottom": {
          "optional": false,
          "value": 25
        },
        "right": {
          "optional": false,
          "value": 25
        }
      }
    },
    {
      "kind": "union",
      "values": [
        83,
        84,
        85,
        86
      ]
    },
    {
      "kind": "object",
      "properties": {
        "type": {
          "optional": false,
          "value": 73
        },
        "shape": {
          "optional": false,
          "value": 76
        },
        "size": {
          "optional": false,
          "value": 82
        },
        "position": {
          "optional": false,
          "value": 87
        },
        "colorStops": {
          "optional": false,
          "value": 71
        }
      }
    },
    {
      "kind": "union",
      "values": [
        72,
        88
      ]
    },
    {
      "kind": "array",
      "value": 89
    },
    {
      "kind": "union",
      "values": [
        0,
        3,
        90
      ]
    },
    {
      "kind": "array",
      "value": 81
    },
    {
      "kind": "union",
      "values": [
        0,
        3,
        92
      ]
    },
    {
      "kind": "array",
      "value": 87
    },
    {
      "kind": "union",
      "values": [
        0,
        3,
        94
      ]
    },
    {
      "kind": "literal",
      "value": "repeat"
    },
    {
      "kind": "literal",
      "value": "space"
    },
    {
      "kind": "literal",
      "value": "round"
    },
    {
      "kind": "literal",
      "value": "no-repeat"
    },
    {
      "kind": "union",
      "values": [
        96,
        97,
        98,
        99
      ]
    },
    {
      "kind": "object",
      "properties": {
        "x": {
          "optional": false,
          "value": 100
        },
        "y": {
          "optional": false,
          "value": 100
        }
      }
    },
    {
      "kind": "array",
      "value": 101
    },
    {
      "kind": "union",
      "values": [
        0,
        3,
        102
      ]
    },
    {
      "kind": "literal",
      "value": "stretch"
    },
    {
      "kind": "literal",
      "value": "center"
    },
    {
      "kind": "literal",
      "value": "flex-start"
    },
    {
      "kind": "literal",
      "value": "flex-end"
    },
    {
      "kind": "literal",
      "value": "space-between"
    },
    {
      "kind": "literal",
      "value": "space-around"
    },
    {
      "kind": "literal",
      "value": "space-evenly"
    },
    {
      "kind": "union",
      "values": [
        0,
        104,
        105,
        106,
        107,
        108,
        109,
        110
      ]
    },
    {
      "kind": "literal",
      "value": "baseline"
    },
    {
      "kind": "union",
      "values": [
        0,
        104,
        105,
        106,
        107,
        112
      ]
    },
    {
      "kind": "union",
      "values": [
        0,
        104,
        105,
        106,
        107,
        112,
        17
      ]
    },
    {
      "kind": "percentage"
    },
    {
      "kind": "union",
      "values": [
        0,
        66,
        1,
        115,
        17
      ]
    },
    {
      "kind": "literal",
      "value": "border-box"
    },
    {
      "kind": "literal",
      "value": "content-box"
    },
    {
      "kind": "union",
      "values": [
        0,
        117,
        118
      ]
    },
    {
      "kind": "literal",
      "value": "flex"
    },
    {
      "kind": "literal",
      "value": "contents"
    },
    {
      "kind": "union",
      "values": [
        0,
        16,
        120,
        121
      ]
    },
    {
      "kind": "literal",
      "value": "row"
    },
    {
      "kind": "literal",
      "value": "column"
    },
    {
      "kind": "literal",
      "value": "row-reverse"
    },
    {
      "kind": "literal",
      "value": "column-reverse"
    },
    {
      "kind": "union",
      "values": [
        0,
        123,
        124,
        125,
        126
      ]
    },
    {
      "kind": "literal",
      "value": "wrap"
    },
    {
      "kind": "literal",
      "value": "nowrap"
    },
    {
      "kind": "literal",
      "value": "wrap-reverse"
    },
    {
      "kind": "union",
      "values": [
        0,
        128,
        129,
        130
      ]
    },
    {
      "kind": "union",
      "values": [
        0,
        105,
        106,
        107,
        108,
        109,
        110
      ]
    },
    {
      "kind": "literal",
      "value": "scroll"
    },
    {
      "kind": "union",
      "values": [
        0,
        5,
        6,
        133
      ]
    },
    {
      "kind": "literal",
      "value": "absolute"
    },
    {
      "kind": "literal",
      "value": "relative"
    },
    {
      "kind": "literal",
      "value": "static"
    },
    {
      "kind": "union",
      "values": [
        0,
        135,
        136,
        137
      ]
    },
    {
      "kind": "literal",
      "value": "inherit"
    },
    {
      "kind": "literal",
      "value": "ltr"
    },
    {
      "kind": "literal",
      "value": "rtl"
    },
    {
      "kind": "union",
      "values": [
        0,
        139,
        140,
        141
      ]
    },
    {
      "kind": "object",
      "properties": {
        "width": {
          "optional": false,
          "value": 1
        },
        "height": {
          "optional": false,
          "value": 1
        }
      }
    },
    {
      "kind": "union",
      "values": [
        0,
        143
      ]
    },
    {
      "kind": "literal",
      "value": "small-caps"
    },
    {
      "kind": "literal",
      "value": "oldstyle-nums"
    },
    {
      "kind": "literal",
      "value": "lining-nums"
    },
    {
      "kind": "literal",
      "value": "tabular-nums"
    },
    {
      "kind": "literal",
      "value": "common-ligatures"
    },
    {
      "kind": "literal",
      "value": "no-common-ligatures"
    },
    {
      "kind": "literal",
      "value": "discretionary-ligatures"
    },
    {
      "kind": "literal",
      "value": "no-discretionary-ligatures"
    },
    {
      "kind": "literal",
      "value": "historical-ligatures"
    },
    {
      "kind": "literal",
      "value": "no-historical-ligatures"
    },
    {
      "kind": "literal",
      "value": "contextual"
    },
    {
      "kind": "literal",
      "value": "no-contextual"
    },
    {
      "kind": "literal",
      "value": "proportional-nums"
    },
    {
      "kind": "literal",
      "value": "stylistic-one"
    },
    {
      "kind": "literal",
      "value": "stylistic-two"
    },
    {
      "kind": "literal",
      "value": "stylistic-three"
    },
    {
      "kind": "literal",
      "value": "stylistic-four"
    },
    {
      "kind": "literal",
      "value": "stylistic-five"
    },
    {
      "kind": "literal",
      "value": "stylistic-six"
    },
    {
      "kind": "literal",
      "value": "stylistic-seven"
    },
    {
      "kind": "literal",
      "value": "stylistic-eight"
    },
    {
      "kind": "literal",
      "value": "stylistic-nine"
    },
    {
      "kind": "literal",
      "value": "stylistic-ten"
    },
    {
      "kind": "literal",
      "value": "stylistic-eleven"
    },
    {
      "kind": "literal",
      "value": "stylistic-twelve"
    },
    {
      "kind": "literal",
      "value": "stylistic-thirteen"
    },
    {
      "kind": "literal",
      "value": "stylistic-fourteen"
    },
    {
      "kind": "literal",
      "value": "stylistic-fifteen"
    },
    {
      "kind": "literal",
      "value": "stylistic-sixteen"
    },
    {
      "kind": "literal",
      "value": "stylistic-seventeen"
    },
    {
      "kind": "literal",
      "value": "stylistic-eighteen"
    },
    {
      "kind": "literal",
      "value": "stylistic-nineteen"
    },
    {
      "kind": "literal",
      "value": "stylistic-twenty"
    },
    {
      "kind": "union",
      "values": [
        145,
        146,
        147,
        148,
        149,
        150,
        151,
        152,
        153,
        154,
        155,
        156,
        157,
        158,
        159,
        160,
        161,
        162,
        163,
        164,
        165,
        166,
        167,
        168,
        169,
        170,
        171,
        172,
        173,
        174,
        175,
        176,
        177
      ]
    },
    {
      "kind": "array",
      "value": 178
    },
    {
      "kind": "union",
      "values": [
        0,
        179
      ]
    },
    {
      "kind": "literal",
      "value": "double"
    },
    {
      "kind": "literal",
      "value": "wavy"
    },
    {
      "kind": "union",
      "values": [
        0,
        12,
        13,
        14,
        181,
        182
      ]
    },
    {
      "kind": "union",
      "values": [
        0,
        17,
        140,
        141
      ]
    },
    {
      "kind": "literal",
      "value": "bottom"
    },
    {
      "kind": "literal",
      "value": "top"
    },
    {
      "kind": "union",
      "values": [
        0,
        105,
        17,
        185,
        186
      ]
    },
    {
      "kind": "literal",
      "value": "middle"
    },
    {
      "kind": "union",
      "values": [
        0,
        17,
        185,
        186,
        188
      ]
    },
    {
      "kind": "literal",
      "value": "italic"
    },
    {
      "kind": "union",
      "values": [
        0,
        47,
        190
      ]
    },
    {
      "kind": "literal",
      "value": "bold"
    },
    {
      "kind": "literal",
      "value": "100"
    },
    {
      "kind": "literal",
      "value": "200"
    },
    {
      "kind": "literal",
      "value": "300"
    },
    {
      "kind": "literal",
      "value": "400"
    },
    {
      "kind": "literal",
      "value": "500"
    },
    {
      "kind": "literal",
      "value": "600"
    },
    {
      "kind": "literal",
      "value": "700"
    },
    {
      "kind": "literal",
      "value": "800"
    },
    {
      "kind": "literal",
      "value": "900"
    },
    {
      "kind": "literal",
      "value": 100
    },
    {
      "kind": "literal",
      "value": 200
    },
    {
      "kind": "literal",
      "value": 300
    },
    {
      "kind": "literal",
      "value": 400
    },
    {
      "kind": "literal",
      "value": 500
    },
    {
      "kind": "literal",
      "value": 600
    },
    {
      "kind": "literal",
      "value": 700
    },
    {
      "kind": "literal",
      "value": 800
    },
    {
      "kind": "literal",
      "value": 900
    },
    {
      "kind": "literal",
      "value": "ultralight"
    },
    {
      "kind": "literal",
      "value": "thin"
    },
    {
      "kind": "literal",
      "value": "light"
    },
    {
      "kind": "literal",
      "value": "medium"
    },
    {
      "kind": "literal",
      "value": "regular"
    },
    {
      "kind": "literal",
      "value": "semibold"
    },
    {
      "kind": "literal",
      "value": "condensedBold"
    },
    {
      "kind": "literal",
      "value": "condensed"
    },
    {
      "kind": "literal",
      "value": "heavy"
    },
    {
      "kind": "literal",
      "value": "black"
    },
    {
      "kind": "union",
      "values": [
        0,
        47,
        192,
        193,
        194,
        195,
        196,
        197,
        198,
        199,
        200,
        201,
        202,
        203,
        204,
        205,
        206,
        207,
        208,
        209,
        210,
        211,
        212,
        213,
        214,
        215,
        216,
        217,
        218,
        219,
        220
      ]
    },
    {
      "kind": "literal",
      "value": "end"
    },
    {
      "kind": "literal",
      "value": "left"
    },
    {
      "kind": "literal",
      "value": "right"
    },
    {
      "kind": "literal",
      "value": "start"
    },
    {
      "kind": "literal",
      "value": "justify"
    },
    {
      "kind": "union",
      "values": [
        0,
        105,
        17,
        222,
        223,
        224,
        225,
        226
      ]
    },
    {
      "kind": "literal",
      "value": "underline"
    },
    {
      "kind": "literal",
      "value": "line-through"
    },
    {
      "kind": "literal",
      "value": "underline line-through"
    },
    {
      "kind": "union",
      "values": [
        0,
        16,
        228,
        229,
        230
      ]
    },
    {
      "kind": "literal",
      "value": "capitalize"
    },
    {
      "kind": "literal",
      "value": "uppercase"
    },
    {
      "kind": "literal",
      "value": "lowercase"
    },
    {
      "kind": "union",
      "values": [
        0,
        16,
        232,
        233,
        234
      ]
    },
    {
      "kind": "literal",
      "value": "contain"
    },
    {
      "kind": "literal",
      "value": "text"
    },
    {
      "kind": "literal",
      "value": "all"
    },
    {
      "kind": "union",
      "values": [
        0,
        236,
        16,
        17,
        237,
        238
      ]
    },
    {
      "kind": "literal",
      "value": "cover"
    },
    {
      "kind": "union",
      "values": [
        0,
        240,
        236,
        104,
        96,
        105,
        16
      ]
    },
    {
      "kind": "literal",
      "value": "fill"
    },
    {
      "kind": "literal",
      "value": "scale-down"
    },
    {
      "kind": "union",
      "values": [
        0,
        240,
        236,
        16,
        242,
        243
      ]
    },
    {
      "kind": "object",
      "properties": {
        "perspective": {
          "optional": false,
          "value": 1
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "rotate": {
          "optional": false,
          "value": 3
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "rotateX": {
          "optional": false,
          "value": 3
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "rotateY": {
          "optional": false,
          "value": 3
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "rotateZ": {
          "optional": false,
          "value": 3
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "scale": {
          "optional": false,
          "value": 1
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "scaleX": {
          "optional": false,
          "value": 1
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "scaleY": {
          "optional": false,
          "value": 1
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "union",
      "values": [
        1,
        115
      ]
    },
    {
      "kind": "object",
      "properties": {
        "translateX": {
          "optional": false,
          "value": 253
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "translateY": {
          "optional": false,
          "value": 253
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "skewX": {
          "optional": false,
          "value": 3
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "object",
      "properties": {
        "skewY": {
          "optional": false,
          "value": 3
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "matrix": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "array",
      "value": 1
    },
    {
      "kind": "object",
      "properties": {
        "matrix": {
          "optional": false,
          "value": 258
        },
        "perspective": {
          "optional": true,
          "value": 0
        },
        "rotate": {
          "optional": true,
          "value": 0
        },
        "rotateX": {
          "optional": true,
          "value": 0
        },
        "rotateY": {
          "optional": true,
          "value": 0
        },
        "rotateZ": {
          "optional": true,
          "value": 0
        },
        "scale": {
          "optional": true,
          "value": 0
        },
        "scaleX": {
          "optional": true,
          "value": 0
        },
        "scaleY": {
          "optional": true,
          "value": 0
        },
        "translateX": {
          "optional": true,
          "value": 0
        },
        "translateY": {
          "optional": true,
          "value": 0
        },
        "skewX": {
          "optional": true,
          "value": 0
        },
        "skewY": {
          "optional": true,
          "value": 0
        }
      }
    },
    {
      "kind": "union",
      "values": [
        245,
        246,
        247,
        248,
        249,
        250,
        251,
        252,
        254,
        255,
        256,
        257,
        259
      ]
    },
    {
      "kind": "array",
      "value": 260
    },
    {
      "kind": "union",
      "values": [
        0,
        3,
        261
      ]
    },
    {
      "kind": "array",
      "value": 25
    },
    {
      "kind": "union",
      "values": [
        0,
        3,
        263
      ]
    },
    {
      "kind": "union",
      "values": [
        0,
        258
      ]
    },
    {
      "kind": "object",
      "properties": {
        "flex": {
          "optional": true,
          "value": 2
        },
        "scaleX": {
          "optional": true,
          "value": 2
        },
        "scaleY": {
          "optional": true,
          "value": 2
        },
        "translateX": {
          "optional": true,
          "value": 2
        },
        "translateY": {
          "optional": true,
          "value": 2
        },
        "color": {
          "optional": true,
          "value": 4
        },
        "backfaceVisibility": {
          "optional": true,
          "value": 7
        },
        "backgroundColor": {
          "optional": true,
          "value": 4
        },
        "borderBlockColor": {
          "optional": true,
          "value": 4
        },
        "borderBlockEndColor": {
          "optional": true,
          "value": 4
        },
        "borderBlockStartColor": {
          "optional": true,
          "value": 4
        },
        "borderBottomColor": {
          "optional": true,
          "value": 4
        },
        "borderBottomEndRadius": {
          "optional": true,
          "value": 8
        },
        "borderBottomLeftRadius": {
          "optional": true,
          "value": 8
        },
        "borderBottomRightRadius": {
          "optional": true,
          "value": 8
        },
        "borderBottomStartRadius": {
          "optional": true,
          "value": 8
        },
        "borderColor": {
          "optional": true,
          "value": 4
        },
        "borderCurve": {
          "optional": true,
          "value": 11
        },
        "borderEndColor": {
          "optional": true,
          "value": 4
        },
        "borderEndEndRadius": {
          "optional": true,
          "value": 8
        },
        "borderEndStartRadius": {
          "optional": true,
          "value": 8
        },
        "borderLeftColor": {
          "optional": true,
          "value": 4
        },
        "borderRadius": {
          "optional": true,
          "value": 8
        },
        "borderRightColor": {
          "optional": true,
          "value": 4
        },
        "borderStartColor": {
          "optional": true,
          "value": 4
        },
        "borderStartEndRadius": {
          "optional": true,
          "value": 8
        },
        "borderStartStartRadius": {
          "optional": true,
          "value": 8
        },
        "borderStyle": {
          "optional": true,
          "value": 15
        },
        "borderTopColor": {
          "optional": true,
          "value": 4
        },
        "borderTopEndRadius": {
          "optional": true,
          "value": 8
        },
        "borderTopLeftRadius": {
          "optional": true,
          "value": 8
        },
        "borderTopRightRadius": {
          "optional": true,
          "value": 8
        },
        "borderTopStartRadius": {
          "optional": true,
          "value": 8
        },
        "outlineColor": {
          "optional": true,
          "value": 4
        },
        "outlineOffset": {
          "optional": true,
          "value": 2
        },
        "outlineStyle": {
          "optional": true,
          "value": 15
        },
        "outlineWidth": {
          "optional": true,
          "value": 2
        },
        "opacity": {
          "optional": true,
          "value": 2
        },
        "elevation": {
          "optional": true,
          "value": 2
        },
        "pointerEvents": {
          "optional": true,
          "value": 20
        },
        "isolation": {
          "optional": true,
          "value": 22
        },
        "cursor": {
          "optional": true,
          "value": 24
        },
        "boxShadow": {
          "optional": true,
          "value": 31
        },
        "filter": {
          "optional": true,
          "value": 46
        },
        "mixBlendMode": {
          "optional": true,
          "value": 64
        },
        "backgroundImage": {
          "optional": true,
          "value": 91
        },
        "experimental_backgroundImage": {
          "optional": true,
          "value": 91
        },
        "experimental_backgroundSize": {
          "optional": true,
          "value": 93
        },
        "experimental_backgroundPosition": {
          "optional": true,
          "value": 95
        },
        "experimental_backgroundRepeat": {
          "optional": true,
          "value": 103
        },
        "alignContent": {
          "optional": true,
          "value": 111
        },
        "alignItems": {
          "optional": true,
          "value": 113
        },
        "alignSelf": {
          "optional": true,
          "value": 114
        },
        "aspectRatio": {
          "optional": true,
          "value": 8
        },
        "borderBottomWidth": {
          "optional": true,
          "value": 2
        },
        "borderEndWidth": {
          "optional": true,
          "value": 2
        },
        "borderLeftWidth": {
          "optional": true,
          "value": 2
        },
        "borderRightWidth": {
          "optional": true,
          "value": 2
        },
        "borderStartWidth": {
          "optional": true,
          "value": 2
        },
        "borderTopWidth": {
          "optional": true,
          "value": 2
        },
        "borderWidth": {
          "optional": true,
          "value": 2
        },
        "bottom": {
          "optional": true,
          "value": 116
        },
        "boxSizing": {
          "optional": true,
          "value": 119
        },
        "display": {
          "optional": true,
          "value": 122
        },
        "end": {
          "optional": true,
          "value": 116
        },
        "flexBasis": {
          "optional": true,
          "value": 116
        },
        "flexDirection": {
          "optional": true,
          "value": 127
        },
        "rowGap": {
          "optional": true,
          "value": 8
        },
        "gap": {
          "optional": true,
          "value": 8
        },
        "columnGap": {
          "optional": true,
          "value": 8
        },
        "flexGrow": {
          "optional": true,
          "value": 2
        },
        "flexShrink": {
          "optional": true,
          "value": 2
        },
        "flexWrap": {
          "optional": true,
          "value": 131
        },
        "height": {
          "optional": true,
          "value": 116
        },
        "justifyContent": {
          "optional": true,
          "value": 132
        },
        "left": {
          "optional": true,
          "value": 116
        },
        "margin": {
          "optional": true,
          "value": 116
        },
        "marginBottom": {
          "optional": true,
          "value": 116
        },
        "marginEnd": {
          "optional": true,
          "value": 116
        },
        "marginHorizontal": {
          "optional": true,
          "value": 116
        },
        "marginLeft": {
          "optional": true,
          "value": 116
        },
        "marginRight": {
          "optional": true,
          "value": 116
        },
        "marginStart": {
          "optional": true,
          "value": 116
        },
        "marginTop": {
          "optional": true,
          "value": 116
        },
        "marginVertical": {
          "optional": true,
          "value": 116
        },
        "maxHeight": {
          "optional": true,
          "value": 116
        },
        "maxWidth": {
          "optional": true,
          "value": 116
        },
        "minHeight": {
          "optional": true,
          "value": 116
        },
        "minWidth": {
          "optional": true,
          "value": 116
        },
        "overflow": {
          "optional": true,
          "value": 134
        },
        "padding": {
          "optional": true,
          "value": 116
        },
        "paddingBottom": {
          "optional": true,
          "value": 116
        },
        "paddingEnd": {
          "optional": true,
          "value": 116
        },
        "paddingHorizontal": {
          "optional": true,
          "value": 116
        },
        "paddingLeft": {
          "optional": true,
          "value": 116
        },
        "paddingRight": {
          "optional": true,
          "value": 116
        },
        "paddingStart": {
          "optional": true,
          "value": 116
        },
        "paddingTop": {
          "optional": true,
          "value": 116
        },
        "paddingVertical": {
          "optional": true,
          "value": 116
        },
        "position": {
          "optional": true,
          "value": 138
        },
        "right": {
          "optional": true,
          "value": 116
        },
        "start": {
          "optional": true,
          "value": 116
        },
        "top": {
          "optional": true,
          "value": 116
        },
        "width": {
          "optional": true,
          "value": 116
        },
        "zIndex": {
          "optional": true,
          "value": 2
        },
        "direction": {
          "optional": true,
          "value": 142
        },
        "inset": {
          "optional": true,
          "value": 116
        },
        "insetBlock": {
          "optional": true,
          "value": 116
        },
        "insetBlockEnd": {
          "optional": true,
          "value": 116
        },
        "insetBlockStart": {
          "optional": true,
          "value": 116
        },
        "insetInline": {
          "optional": true,
          "value": 116
        },
        "insetInlineEnd": {
          "optional": true,
          "value": 116
        },
        "insetInlineStart": {
          "optional": true,
          "value": 116
        },
        "marginBlock": {
          "optional": true,
          "value": 116
        },
        "marginBlockEnd": {
          "optional": true,
          "value": 116
        },
        "marginBlockStart": {
          "optional": true,
          "value": 116
        },
        "marginInline": {
          "optional": true,
          "value": 116
        },
        "marginInlineEnd": {
          "optional": true,
          "value": 116
        },
        "marginInlineStart": {
          "optional": true,
          "value": 116
        },
        "paddingBlock": {
          "optional": true,
          "value": 116
        },
        "paddingBlockEnd": {
          "optional": true,
          "value": 116
        },
        "paddingBlockStart": {
          "optional": true,
          "value": 116
        },
        "paddingInline": {
          "optional": true,
          "value": 116
        },
        "paddingInlineEnd": {
          "optional": true,
          "value": 116
        },
        "paddingInlineStart": {
          "optional": true,
          "value": 116
        },
        "shadowColor": {
          "optional": true,
          "value": 4
        },
        "shadowOffset": {
          "optional": true,
          "value": 144
        },
        "shadowOpacity": {
          "optional": true,
          "value": 2
        },
        "shadowRadius": {
          "optional": true,
          "value": 2
        },
        "fontVariant": {
          "optional": true,
          "value": 180
        },
        "textDecorationColor": {
          "optional": true,
          "value": 4
        },
        "textDecorationStyle": {
          "optional": true,
          "value": 183
        },
        "writingDirection": {
          "optional": true,
          "value": 184
        },
        "textAlignVertical": {
          "optional": true,
          "value": 187
        },
        "verticalAlign": {
          "optional": true,
          "value": 189
        },
        "includeFontPadding": {
          "optional": true,
          "value": 28
        },
        "fontFamily": {
          "optional": true,
          "value": 4
        },
        "fontSize": {
          "optional": true,
          "value": 2
        },
        "fontStyle": {
          "optional": true,
          "value": 191
        },
        "fontWeight": {
          "optional": true,
          "value": 221
        },
        "letterSpacing": {
          "optional": true,
          "value": 2
        },
        "lineHeight": {
          "optional": true,
          "value": 2
        },
        "textAlign": {
          "optional": true,
          "value": 227
        },
        "textDecorationLine": {
          "optional": true,
          "value": 231
        },
        "textShadowColor": {
          "optional": true,
          "value": 4
        },
        "textShadowOffset": {
          "optional": true,
          "value": 144
        },
        "textShadowRadius": {
          "optional": true,
          "value": 2
        },
        "textTransform": {
          "optional": true,
          "value": 235
        },
        "userSelect": {
          "optional": true,
          "value": 239
        },
        "resizeMode": {
          "optional": true,
          "value": 241
        },
        "overlayColor": {
          "optional": true,
          "value": 4
        },
        "tintColor": {
          "optional": true,
          "value": 4
        },
        "objectFit": {
          "optional": true,
          "value": 244
        },
        "transform": {
          "optional": true,
          "value": 262
        },
        "transformOrigin": {
          "optional": true,
          "value": 264
        },
        "transformMatrix": {
          "optional": true,
          "value": 265
        },
        "rotation": {
          "optional": true,
          "value": 2
        }
      }
    }
  ]
}
