/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


template <typename T>
class JSI_EXPORT NativeZyzzCxxSpec : public TurboModule {
public:
  static constexpr std::string_view kModuleName = "NativeZyzz";

protected:
  NativeZyzzCxxSpec(std::shared_ptr<CallInvoker> jsInvoker) : TurboModule(std::string{NativeZyzzCxxSpec::kModuleName}, jsInvoker) {
    methodMap_["detach"] = MethodMetadata {.argCount = 1, .invoker = __detach};
    methodMap_["inspect"] = MethodMetadata {.argCount = 0, .invoker = __inspect};
    methodMap_["update"] = MethodMetadata {.argCount = 1, .invoker = __update};
  }

private:
  static jsi::Value __detach(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::detach) == 2,
      "Expected detach(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::detach,  static_cast<NativeZyzzCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber());return jsi::Value::undefined();
  }

  static jsi::Value __inspect(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::inspect) == 1,
      "Expected inspect(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Object>(rt, &T::inspect,  static_cast<NativeZyzzCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __update(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::update) == 2,
      "Expected update(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::update,  static_cast<NativeZyzzCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asObject(rt).asArray(rt));return jsi::Value::undefined();
  }
};

} // namespace facebook::react
