/** Describes shorthand conflicts and reset-only relationships for ordered CSS emission. @module */

/** Reviewed longhand domains, including reset-only properties omitted by shorthand grammars. */
export const shorthands = {
  animation: [
    'animationName',
    'animationDuration',
    'animationTimingFunction',
    'animationDelay',
    'animationIterationCount',
    'animationDirection',
    'animationFillMode',
    'animationPlayState',
    'animationTimeline',
    'animationRange',
    'animationTrigger',
  ],
  animationRange: ['animationRangeStart', 'animationRangeEnd'],
  background: [
    'backgroundImage',
    'backgroundPosition',
    'backgroundSize',
    'backgroundRepeat',
    'backgroundOrigin',
    'backgroundClip',
    'backgroundAttachment',
    'backgroundColor',
  ],
  border: ['borderWidth', 'borderStyle', 'borderColor', 'borderImage'],
  borderImage: [
    'borderImageSource',
    'borderImageSlice',
    'borderImageWidth',
    'borderImageOutset',
    'borderImageRepeat',
  ],
  caret: ['caretColor', 'caretAnimation', 'caretShape'],
  columns: ['columnWidth', 'columnCount', 'columnHeight'],
  container: ['containerName', 'containerType'],
  flex: ['flexGrow', 'flexShrink', 'flexBasis'],
  font: [
    'fontStyle',
    'fontVariant',
    'fontWeight',
    'fontStretch',
    'fontSize',
    'lineHeight',
    'fontFamily',
    'fontKerning',
    'fontSizeAdjust',
    'fontFeatureSettings',
    'fontLanguageOverride',
    'fontOpticalSizing',
    'fontVariationSettings',
    'fontPalette',
  ],
  fontVariant: [
    'fontVariantAlternates',
    'fontVariantCaps',
    'fontVariantEastAsian',
    'fontVariantEmoji',
    'fontVariantLigatures',
    'fontVariantNumeric',
    'fontVariantPosition',
  ],
  grid: [
    'gridTemplateRows',
    'gridTemplateColumns',
    'gridTemplateAreas',
    'gridAutoRows',
    'gridAutoColumns',
    'gridAutoFlow',
  ],
  gridArea: ['gridRowStart', 'gridColumnStart', 'gridRowEnd', 'gridColumnEnd'],
  gridColumn: ['gridColumnStart', 'gridColumnEnd'],
  gridRow: ['gridRowStart', 'gridRowEnd'],
  gridTemplate: [
    'gridTemplateColumns',
    'gridTemplateRows',
    'gridTemplateAreas',
  ],
  listStyle: ['listStyleType', 'listStylePosition', 'listStyleImage'],
  mask: [
    'maskImage',
    'maskMode',
    'maskRepeat',
    'maskPosition',
    'maskClip',
    'maskOrigin',
    'maskSize',
    'maskComposite',
    'maskBorder',
  ],
  maskBorder: [
    'maskBorderMode',
    'maskBorderOutset',
    'maskBorderRepeat',
    'maskBorderSlice',
    'maskBorderSource',
    'maskBorderWidth',
  ],
  MsContentZoomLimit: ['MsContentZoomLimitMax', 'MsContentZoomLimitMin'],
  MsContentZoomSnap: ['MsContentZoomSnapType', 'MsContentZoomSnapPoints'],
  MsScrollLimit: [
    'MsScrollLimitXMin',
    'MsScrollLimitYMin',
    'MsScrollLimitXMax',
    'MsScrollLimitYMax',
  ],
  MsScrollSnapX: ['MsScrollSnapType', 'MsScrollSnapPointsX'],
  MsScrollSnapY: ['MsScrollSnapType', 'MsScrollSnapPointsY'],
  offset: [
    'offsetPosition',
    'offsetPath',
    'offsetDistance',
    'offsetAnchor',
    'offsetRotate',
  ],
  placeContent: ['alignContent', 'justifyContent'],
  placeItems: ['alignItems', 'justifyItems'],
  placeSelf: ['alignSelf', 'justifySelf'],
  positionTry: ['positionTryFallbacks', 'positionTryOrder'],
  scrollTimeline: ['scrollTimelineName', 'scrollTimelineAxis'],
  textBox: ['textBoxTrim', 'textBoxEdge'],
  textDecoration: [
    'textDecorationColor',
    'textDecorationStyle',
    'textDecorationLine',
    'textDecorationThickness',
  ],
  textEmphasis: ['textEmphasisStyle', 'textEmphasisColor'],
  timelineTrigger: [
    'timelineTriggerName',
    'timelineTriggerSource',
    'timelineTriggerActivationRange',
    'timelineTriggerActiveRange',
  ],
  timelineTriggerActivationRange: [
    'timelineTriggerActivationRangeStart',
    'timelineTriggerActivationRangeEnd',
  ],
  timelineTriggerActiveRange: [
    'timelineTriggerActiveRangeStart',
    'timelineTriggerActiveRangeEnd',
  ],
  transition: [
    'transitionDelay',
    'transitionDuration',
    'transitionProperty',
    'transitionTimingFunction',
    'transitionBehavior',
  ],
  viewTimeline: ['viewTimelineName', 'viewTimelineAxis', 'viewTimelineInset'],
  WebkitMask: [
    'WebkitMaskImage',
    'WebkitMaskRepeat',
    'WebkitMaskAttachment',
    'WebkitMaskPosition',
    'WebkitMaskOrigin',
    'WebkitMaskClip',
    'mask',
    'WebkitMaskSize',
  ],
  WebkitTextStroke: ['WebkitTextStrokeWidth', 'WebkitTextStrokeColor'],
} as const
