/** Static projection of pinned React Native declarations. Animated and opaque host values are excluded. @module */
// Copyright (c) Meta Platforms, Inc. and affiliates. MIT license: test/conformance/native/upstream/LICENSE.
// Generated by scripts/native-conformance.ts --static from React Native 0.87.0.
type ImageResizeMode = 'cover' | 'contain' | 'stretch' | 'repeat' | 'center' | 'none';
type FlexAlignType = 'flex-start' | 'flex-end' | 'center' | 'stretch' | 'baseline';
type DimensionValue = number | 'auto' | `${number}%` | never | null;
type AnimatableNumericValue = number | never;
type AnimatableStringValue = string | never;
type CursorValue = 'auto' | 'pointer';
interface FlexStyle {
    alignContent?: 'flex-start' | 'flex-end' | 'center' | 'stretch' | 'space-between' | 'space-around' | 'space-evenly' | undefined;
    alignItems?: FlexAlignType | undefined;
    alignSelf?: 'auto' | FlexAlignType | undefined;
    aspectRatio?: number | string | undefined;
    borderBottomWidth?: number | undefined;
    borderEndWidth?: number | undefined;
    borderLeftWidth?: number | undefined;
    borderRightWidth?: number | undefined;
    borderStartWidth?: number | undefined;
    borderTopWidth?: number | undefined;
    borderWidth?: number | undefined;
    bottom?: DimensionValue | undefined;
    boxSizing?: 'border-box' | 'content-box' | undefined;
    display?: 'none' | 'flex' | 'contents' | undefined;
    end?: DimensionValue | undefined;
    flex?: number | undefined;
    flexBasis?: DimensionValue | undefined;
    flexDirection?: 'row' | 'column' | 'row-reverse' | 'column-reverse' | undefined;
    rowGap?: number | string | undefined;
    gap?: number | string | undefined;
    columnGap?: number | string | undefined;
    flexGrow?: number | undefined;
    flexShrink?: number | undefined;
    flexWrap?: 'wrap' | 'nowrap' | 'wrap-reverse' | undefined;
    height?: DimensionValue | undefined;
    justifyContent?: 'flex-start' | 'flex-end' | 'center' | 'space-between' | 'space-around' | 'space-evenly' | undefined;
    left?: DimensionValue | undefined;
    margin?: DimensionValue | undefined;
    marginBottom?: DimensionValue | undefined;
    marginEnd?: DimensionValue | undefined;
    marginHorizontal?: DimensionValue | undefined;
    marginLeft?: DimensionValue | undefined;
    marginRight?: DimensionValue | undefined;
    marginStart?: DimensionValue | undefined;
    marginTop?: DimensionValue | undefined;
    marginVertical?: DimensionValue | undefined;
    maxHeight?: DimensionValue | undefined;
    maxWidth?: DimensionValue | undefined;
    minHeight?: DimensionValue | undefined;
    minWidth?: DimensionValue | undefined;
    overflow?: 'visible' | 'hidden' | 'scroll' | undefined;
    padding?: DimensionValue | undefined;
    paddingBottom?: DimensionValue | undefined;
    paddingEnd?: DimensionValue | undefined;
    paddingHorizontal?: DimensionValue | undefined;
    paddingLeft?: DimensionValue | undefined;
    paddingRight?: DimensionValue | undefined;
    paddingStart?: DimensionValue | undefined;
    paddingTop?: DimensionValue | undefined;
    paddingVertical?: DimensionValue | undefined;
    position?: 'absolute' | 'relative' | 'static' | undefined;
    right?: DimensionValue | undefined;
    start?: DimensionValue | undefined;
    top?: DimensionValue | undefined;
    width?: DimensionValue | undefined;
    zIndex?: number | undefined;
    direction?: 'inherit' | 'ltr' | 'rtl' | undefined;
    inset?: DimensionValue | undefined;
    insetBlock?: DimensionValue | undefined;
    insetBlockEnd?: DimensionValue | undefined;
    insetBlockStart?: DimensionValue | undefined;
    insetInline?: DimensionValue | undefined;
    insetInlineEnd?: DimensionValue | undefined;
    insetInlineStart?: DimensionValue | undefined;
    marginBlock?: DimensionValue | undefined;
    marginBlockEnd?: DimensionValue | undefined;
    marginBlockStart?: DimensionValue | undefined;
    marginInline?: DimensionValue | undefined;
    marginInlineEnd?: DimensionValue | undefined;
    marginInlineStart?: DimensionValue | undefined;
    paddingBlock?: DimensionValue | undefined;
    paddingBlockEnd?: DimensionValue | undefined;
    paddingBlockStart?: DimensionValue | undefined;
    paddingInline?: DimensionValue | undefined;
    paddingInlineEnd?: DimensionValue | undefined;
    paddingInlineStart?: DimensionValue | undefined;
}
interface ShadowStyleIOS {
    shadowColor?: ColorValue | undefined;
    shadowOffset?: Readonly<{
        width: number;
        height: number;
    }> | undefined;
    shadowOpacity?: AnimatableNumericValue | undefined;
    shadowRadius?: number | undefined;
}
interface PerspectiveTransform {
    perspective: AnimatableNumericValue;
}
interface RotateTransform {
    rotate: AnimatableStringValue;
}
interface RotateXTransform {
    rotateX: AnimatableStringValue;
}
interface RotateYTransform {
    rotateY: AnimatableStringValue;
}
interface RotateZTransform {
    rotateZ: AnimatableStringValue;
}
interface ScaleTransform {
    scale: AnimatableNumericValue;
}
interface ScaleXTransform {
    scaleX: AnimatableNumericValue;
}
interface ScaleYTransform {
    scaleY: AnimatableNumericValue;
}
interface TranslateXTransform {
    translateX: AnimatableNumericValue | `${number}%`;
}
interface TranslateYTransform {
    translateY: AnimatableNumericValue | `${number}%`;
}
interface SkewXTransform {
    skewX: AnimatableStringValue;
}
interface SkewYTransform {
    skewY: AnimatableStringValue;
}
interface MatrixTransform {
    matrix: AnimatableNumericValue[];
}
interface TransformsStyle {
    transform?: Readonly<MaximumOneOf<PerspectiveTransform & RotateTransform & RotateXTransform & RotateYTransform & RotateZTransform & ScaleTransform & ScaleXTransform & ScaleYTransform & TranslateXTransform & TranslateYTransform & SkewXTransform & SkewYTransform & MatrixTransform>[]> | string | undefined;
    transformOrigin?: Array<string | number> | string | undefined;
    transformMatrix?: Array<number> | undefined;
    rotation?: AnimatableNumericValue | undefined;
    scaleX?: AnimatableNumericValue | undefined;
    scaleY?: AnimatableNumericValue | undefined;
    translateX?: AnimatableNumericValue | undefined;
    translateY?: AnimatableNumericValue | undefined;
}
type FilterFunction = {
    brightness: number | string;
} | {
    blur: number | string;
} | {
    contrast: number | string;
} | {
    grayscale: number | string;
} | {
    hueRotate: number | string;
} | {
    invert: number | string;
} | {
    opacity: number | string;
} | {
    saturate: number | string;
} | {
    sepia: number | string;
} | {
    dropShadow: DropShadowValue | string;
};
type DropShadowValue = {
    offsetX: number | string;
    offsetY: number | string;
    standardDeviation?: number | string | undefined;
    color?: ColorValue | number | undefined;
};
type BoxShadowValue = {
    offsetX: number | string;
    offsetY: number | string;
    color?: ColorValue | undefined;
    blurRadius?: string | number | undefined;
    spreadDistance?: number | string | undefined;
    inset?: boolean | undefined;
};
type BlendMode = 'normal' | 'multiply' | 'screen' | 'overlay' | 'darken' | 'lighten' | 'color-dodge' | 'color-burn' | 'hard-light' | 'soft-light' | 'difference' | 'exclusion' | 'hue' | 'saturation' | 'color' | 'luminosity' | 'plus-lighter';
type LinearGradientValue = {
    type: 'linear-gradient';
    direction?: string | undefined;
    colorStops: ReadonlyArray<{
        color: ColorValue | null;
        positions?: ReadonlyArray<string> | undefined;
    }>;
};
type GradientValue = LinearGradientValue;
type RadialExtent = 'closest-corner' | 'closest-side' | 'farthest-corner' | 'farthest-side';
type RadialGradientPosition = {
    top: number | string;
    left: number | string;
} | {
    top: number | string;
    right: number | string;
} | {
    bottom: number | string;
    left: number | string;
} | {
    bottom: number | string;
    right: number | string;
};
type RadialGradientShape = 'circle' | 'ellipse';
type RadialGradientSize = RadialExtent | {
    x: string | number;
    y: string | number;
};
type RadialGradientValue = {
    type: 'radial-gradient';
    shape: RadialGradientShape;
    size: RadialGradientSize;
    position: RadialGradientPosition;
    colorStops: ReadonlyArray<{
        color: ColorValue | null;
        positions?: ReadonlyArray<string> | undefined;
    }>;
};
type BackgroundImageValue = LinearGradientValue | RadialGradientValue;
type BackgroundSizeValue = {
    x: string | number;
    y: string | number;
};
type BackgroundRepeatKeyword = 'repeat' | 'space' | 'round' | 'no-repeat';
type BackgroundPositionValue = {
    top: number | string;
    left: number | string;
} | {
    top: number | string;
    right: number | string;
} | {
    bottom: number | string;
    left: number | string;
} | {
    bottom: number | string;
    right: number | string;
};
type BackgroundRepeatValue = {
    x: BackgroundRepeatKeyword;
    y: BackgroundRepeatKeyword;
};
interface ViewStyle extends FlexStyle, ShadowStyleIOS, TransformsStyle {
    backfaceVisibility?: 'visible' | 'hidden' | undefined;
    backgroundColor?: ColorValue | undefined;
    borderBlockColor?: ColorValue | undefined;
    borderBlockEndColor?: ColorValue | undefined;
    borderBlockStartColor?: ColorValue | undefined;
    borderBottomColor?: ColorValue | undefined;
    borderBottomEndRadius?: AnimatableNumericValue | string | undefined;
    borderBottomLeftRadius?: AnimatableNumericValue | string | undefined;
    borderBottomRightRadius?: AnimatableNumericValue | string | undefined;
    borderBottomStartRadius?: AnimatableNumericValue | string | undefined;
    borderColor?: ColorValue | undefined;
    borderCurve?: 'circular' | 'continuous' | undefined;
    borderEndColor?: ColorValue | undefined;
    borderEndEndRadius?: AnimatableNumericValue | string | undefined;
    borderEndStartRadius?: AnimatableNumericValue | string | undefined;
    borderLeftColor?: ColorValue | undefined;
    borderRadius?: AnimatableNumericValue | string | undefined;
    borderRightColor?: ColorValue | undefined;
    borderStartColor?: ColorValue | undefined;
    borderStartEndRadius?: AnimatableNumericValue | string | undefined;
    borderStartStartRadius?: AnimatableNumericValue | string | undefined;
    borderStyle?: 'solid' | 'dotted' | 'dashed' | undefined;
    borderTopColor?: ColorValue | undefined;
    borderTopEndRadius?: AnimatableNumericValue | string | undefined;
    borderTopLeftRadius?: AnimatableNumericValue | string | undefined;
    borderTopRightRadius?: AnimatableNumericValue | string | undefined;
    borderTopStartRadius?: AnimatableNumericValue | string | undefined;
    outlineColor?: ColorValue | undefined;
    outlineOffset?: AnimatableNumericValue | undefined;
    outlineStyle?: 'solid' | 'dotted' | 'dashed' | undefined;
    outlineWidth?: AnimatableNumericValue | undefined;
    opacity?: AnimatableNumericValue | undefined;
    elevation?: number | undefined;
    pointerEvents?: 'box-none' | 'none' | 'box-only' | 'auto' | undefined;
    isolation?: 'auto' | 'isolate' | undefined;
    cursor?: CursorValue | undefined;
    boxShadow?: ReadonlyArray<BoxShadowValue> | string | undefined;
    filter?: ReadonlyArray<FilterFunction> | string | undefined;
    mixBlendMode?: BlendMode | undefined;
    backgroundImage?: ReadonlyArray<BackgroundImageValue> | string | undefined;
    experimental_backgroundImage?: ReadonlyArray<BackgroundImageValue> | string | undefined;
    experimental_backgroundSize?: ReadonlyArray<BackgroundSizeValue> | string | undefined;
    experimental_backgroundPosition?: ReadonlyArray<BackgroundPositionValue> | string | undefined;
    experimental_backgroundRepeat?: ReadonlyArray<BackgroundRepeatValue> | string | undefined;
}
type FontVariant = 'small-caps' | 'oldstyle-nums' | 'lining-nums' | 'tabular-nums' | 'common-ligatures' | 'no-common-ligatures' | 'discretionary-ligatures' | 'no-discretionary-ligatures' | 'historical-ligatures' | 'no-historical-ligatures' | 'contextual' | 'no-contextual' | 'proportional-nums' | 'stylistic-one' | 'stylistic-two' | 'stylistic-three' | 'stylistic-four' | 'stylistic-five' | 'stylistic-six' | 'stylistic-seven' | 'stylistic-eight' | 'stylistic-nine' | 'stylistic-ten' | 'stylistic-eleven' | 'stylistic-twelve' | 'stylistic-thirteen' | 'stylistic-fourteen' | 'stylistic-fifteen' | 'stylistic-sixteen' | 'stylistic-seventeen' | 'stylistic-eighteen' | 'stylistic-nineteen' | 'stylistic-twenty';
interface TextStyleIOS extends ViewStyle {
    fontVariant?: FontVariant[] | undefined;
    textDecorationColor?: ColorValue | undefined;
    textDecorationStyle?: 'solid' | 'double' | 'dotted' | 'dashed' | 'wavy' | undefined;
    writingDirection?: 'auto' | 'ltr' | 'rtl' | undefined;
}
interface TextStyleAndroid extends ViewStyle {
    textAlignVertical?: 'auto' | 'top' | 'bottom' | 'center' | undefined;
    verticalAlign?: 'auto' | 'top' | 'bottom' | 'middle' | undefined;
    includeFontPadding?: boolean | undefined;
}
interface TextStyle extends TextStyleIOS, TextStyleAndroid, ViewStyle {
    color?: ColorValue | undefined;
    fontFamily?: string | undefined;
    fontSize?: number | undefined;
    fontStyle?: 'normal' | 'italic' | undefined;
    fontWeight?: 'normal' | 'bold' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | 'ultralight' | 'thin' | 'light' | 'medium' | 'regular' | 'semibold' | 'condensedBold' | 'condensed' | 'heavy' | 'black' | undefined;
    letterSpacing?: number | undefined;
    lineHeight?: number | undefined;
    textAlign?: 'auto' | 'left' | 'right' | 'center' | 'justify' | 'start' | 'end' | undefined;
    textDecorationLine?: 'none' | 'underline' | 'line-through' | 'underline line-through' | undefined;
    textDecorationStyle?: 'solid' | 'double' | 'dotted' | 'dashed' | 'wavy' | undefined;
    textDecorationColor?: ColorValue | undefined;
    textShadowColor?: ColorValue | undefined;
    textShadowOffset?: {
        width: number;
        height: number;
    } | undefined;
    textShadowRadius?: number | undefined;
    textTransform?: 'none' | 'capitalize' | 'uppercase' | 'lowercase' | undefined;
    userSelect?: 'auto' | 'none' | 'text' | 'contain' | 'all' | undefined;
}
interface ImageStyle extends FlexStyle, ShadowStyleIOS, TransformsStyle {
    resizeMode?: ImageResizeMode | undefined;
    backfaceVisibility?: 'visible' | 'hidden' | undefined;
    borderBottomLeftRadius?: AnimatableNumericValue | string | undefined;
    borderBottomRightRadius?: AnimatableNumericValue | string | undefined;
    backgroundColor?: ColorValue | undefined;
    borderColor?: ColorValue | undefined;
    borderRadius?: AnimatableNumericValue | string | undefined;
    borderTopLeftRadius?: AnimatableNumericValue | string | undefined;
    borderTopRightRadius?: AnimatableNumericValue | string | undefined;
    overflow?: 'visible' | 'hidden' | undefined;
    overlayColor?: ColorValue | undefined;
    tintColor?: ColorValue | undefined;
    opacity?: AnimatableNumericValue | undefined;
    objectFit?: 'cover' | 'contain' | 'fill' | 'scale-down' | 'none' | undefined;
    cursor?: CursorValue | undefined;
}
type ColorValue = string;
type MaximumOneOf<T, K extends keyof T = keyof T> = K extends keyof T ? {
    [P in K]: T[K];
} & {
    [P in Exclude<keyof T, K>]?: never;
} : never;
type Styles = ImageStyle | TextStyle | ViewStyle;
type Keys<T> = T extends unknown ? keyof T : never;
type Value<T, K extends PropertyKey> = T extends unknown ? K extends keyof T ? T[K] : never : never;
type Output = {
    [K in Keys<Styles>]?: Value<Styles, K>;
};
type Immutable<T> = T extends object ? {
    readonly [K in keyof T]: Immutable<T[K]>;
} : T;
type Properties = Immutable<Output>;

export type { Output, Properties }
