/** Supported properties and their token domains; shared by types and compilation. */
export const domains = {
  padding: 'space',
  paddingTop: 'space',
  paddingRight: 'space',
  paddingBottom: 'space',
  paddingLeft: 'space',
  paddingInline: 'space',
  paddingBlock: 'space',
  paddingInlineStart: 'space',
  paddingInlineEnd: 'space',
  paddingBlockStart: 'space',
  paddingBlockEnd: 'space',
  margin: 'offset',
  marginTop: 'offset',
  marginRight: 'offset',
  marginBottom: 'offset',
  marginLeft: 'offset',
  marginInline: 'offset',
  marginBlock: 'offset',
  marginInlineStart: 'offset',
  marginInlineEnd: 'offset',
  marginBlockStart: 'offset',
  marginBlockEnd: 'offset',
  gap: 'space',
  rowGap: 'space',
  columnGap: 'space',
  width: 'size',
  height: 'size',
  minWidth: 'size',
  maxWidth: 'size',
  minHeight: 'size',
  maxHeight: 'size',
  inlineSize: 'size',
  blockSize: 'size',
  flexBasis: 'size',
  top: 'offset',
  right: 'offset',
  bottom: 'offset',
  left: 'offset',
  inset: 'offset',
  insetInline: 'offset',
  insetBlock: 'offset',
  color: 'color',
  backgroundColor: 'color',
  borderColor: 'color',
  outlineColor: 'color',
  textDecorationColor: 'color',
  fill: 'color',
  stroke: 'color',
  borderRadius: 'radius',
  borderTopLeftRadius: 'radius',
  borderTopRightRadius: 'radius',
  borderBottomLeftRadius: 'radius',
  borderBottomRightRadius: 'radius',
  borderWidth: 'pixels',
  borderTopWidth: 'pixels',
  borderRightWidth: 'pixels',
  borderBottomWidth: 'pixels',
  borderLeftWidth: 'pixels',
  outlineWidth: 'pixels',
  outlineOffset: 'pixels',
  boxShadow: 'shadow',
  fontFamily: 'font',
  transitionTimingFunction: 'easing',
  transitionDuration: 'duration',
  transitionDelay: 'duration',
  display: 'keyword',
  position: 'keyword',
  boxSizing: 'keyword',
  overflow: 'keyword',
  overflowX: 'keyword',
  overflowY: 'keyword',
  alignItems: 'keyword',
  alignSelf: 'keyword',
  justifyContent: 'keyword',
  justifyItems: 'keyword',
  flexDirection: 'keyword',
  flexWrap: 'keyword',
  borderStyle: 'keyword',
  outlineStyle: 'keyword',
  cursor: 'keyword',
  pointerEvents: 'keyword',
  userSelect: 'keyword',
  visibility: 'keyword',
  textAlign: 'keyword',
  textTransform: 'keyword',
  whiteSpace: 'keyword',
  wordBreak: 'keyword',
  textDecorationLine: 'keyword',
  fontStyle: 'keyword',
  fontVariantNumeric: 'keyword',
  colorScheme: 'keyword',
  objectFit: 'keyword',
  opacity: 'unitless',
  zIndex: 'unitless',
  flexGrow: 'unitless',
  flexShrink: 'unitless',
  order: 'unitless',
  lineHeight: 'unitless',
  fontWeight: 'weight',
  transform: 'arbitrary',
  transitionProperty: 'arbitrary',
  gridTemplateColumns: 'arbitrary',
  gridTemplateRows: 'arbitrary',
  gridColumn: 'arbitrary',
  gridRow: 'arbitrary',
  fontSize: 'arbitrary',
  letterSpacing: 'arbitrary',
  content: 'arbitrary',
} as const

/** Pseudo-classes supported without arbitrary selectors. */
export const pseudos = [
  ':hover',
  ':active',
  ':focus',
  ':focus-visible',
  ':focus-within',
  ':disabled',
  ':checked',
  ':first-child',
  ':last-child',
  '::before',
  '::after',
] as const
