/** Regenerates fixed variable property domains from the public TypeScript contract. @module */
import * as Fs from 'node:fs/promises'
import * as Path from 'node:path'
import * as Ts from 'typescript-api'

const directory = await Fs.mkdtemp(Path.resolve('.fixture-binding-domains-'))
try {
  const file = Path.join(directory, 'probe.ts')

  const kinds = [
    'color',
    'length',
    'number',
    'percentage',
    'signedLength',
    'signedPercentage',
  ] as const

  await Fs.writeFile(
    file,
    `import type * as Binding from '../src/internal/Binding.js';\n${kinds.map((kind) => `type ${kind} = Binding.Properties<'${kind}'>`).join('\n')}`,
  )

  const program = Ts.createProgram([file], {
    strict: true,
    skipLibCheck: true,
    module: Ts.ModuleKind.NodeNext,
    moduleResolution: Ts.ModuleResolutionKind.NodeNext,
    target: Ts.ScriptTarget.ESNext,
  })

  const checker = program.getTypeChecker()
  const properties: Record<string, string[]> = {}

  for (const statement of program.getSourceFile(file)!.statements) {
    if (!Ts.isTypeAliasDeclaration(statement)) continue

    const type = checker.getTypeFromTypeNode(statement.type)
    if (!type.isUnion()) throw new Error('Expected a finite property union.')

    properties[statement.name.text] = type.types
      .filter((type) => type.isStringLiteral())
      .map((type) => (type as Ts.StringLiteralType).value)
      .sort((a, b) =>
        a.toLowerCase() < b.toLowerCase()
          ? -1
          : a.toLowerCase() > b.toLowerCase()
            ? 1
            : 0,
      )

    if (!properties[statement.name.text]!.length)
      throw new Error('Empty property domain.')
  }

  await Fs.writeFile(
    'src/internal/BindingDomains.ts',
    `/** Generated by scripts/binding-domains.ts; property domains only, never CSS value validation. @module */\n/** Standard properties accepting each explicit scalar binding domain. */\nexport const properties = ${JSON.stringify(properties, null, 2)} as const\n`,
  )
} finally {
  await Fs.rm(directory, { recursive: true, force: true })
}
