name: Pull Request
on:
  pull_request:
    types: [closed, opened, ready_for_review, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    if: github.event.action != 'closed'
    name: Verify
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/verify.yml
    secrets: inherit
